#!/bin/bash
# pre commit golang only
# add this config to .gitconfig
# [core]
#	hooksPath = /home/muhfaris/.githooks
STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
    goimports -w "$FILE"

    go test -v ./...
    if [[ $? != 0 ]]; then
        PASS=false
    fi

done


if ! $PASS; then
  printf "COMMIT FAILED\n"
  exit 1
else
  printf "COMMIT SUCCEEDED\n"
fi

exit 0
