source ~/.config/nvim/plugin.vim
source ~/.config/nvim/configuration/vim/general.vim
source ~/.config/nvim/configuration/vim/toggleterm.vim
source ~/.config/nvim/configuration/vim/go.vim
source ~/.config/nvim/configuration/vim/formatter.vim
source ~/.config/nvim/configuration/vim/tagbar.vim
source ~/.config/nvim/configuration/vim/telescope.vim
source ~/.config/nvim/configuration/vim/nvim-comment.vim
source ~/.config/nvim/configuration/vim/vimspector.vim

luafile ~/.config/nvim/configuration/lua/nvim-tree.lua
luafile ~/.config/nvim/configuration/lua/devicons.lua
luafile ~/.config/nvim/configuration/lua/toggleterm.lua
luafile ~/.config/nvim/configuration/lua/go.lua
luafile ~/.config/nvim/configuration/lua/nvim-cmp.lua
luafile ~/.config/nvim/configuration/lua/lualine.lua
luafile ~/.config/nvim/configuration/lua/nvim-lsp.lua
luafile ~/.config/nvim/configuration/lua/formatter.lua
luafile ~/.config/nvim/configuration/lua/gitsings.lua
luafile ~/.config/nvim/configuration/lua/telescope.lua
luafile ~/.config/nvim/configuration/lua/nvim-comment.lua
luafile ~/.config/nvim/configuration/lua/tabby.lua
luafile ~/.config/nvim/configuration/lua/which-key.lua
luafile ~/.config/nvim/configuration/lua/dracula.lua
